# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
 schedule:
    - cron: "*/1440 * * * *"
 workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update...
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "qwillie64"
          GITHUB_TOKEN: ${{ secrets.mytoken }}
          TARGET_REPOS: '[]'
          EVENT_LIMIT: 100
